#!/usr/bin/env python3
"""Summarize one article with Claude Code (subscription) and open an HTML card.

Invoked by the widget's ✨ button via Übersicht's run():
    python3 summarize.py "<url>" "<title>"

It fetches the article, asks the Claude Code CLI (`claude -p`) — which runs on
your Claude subscription, NOT the paid API — for a tight summary aimed at a DBMS
hacker, writes an HTML card to a temp file, and opens it (the "window" with the
key info + a link back to the article).

No API key or `anthropic` package needed: it reuses the `claude` binary bundled
with the Cursor/VS Code Claude Code extension (already logged in to your subscription).
"""
from __future__ import annotations

import glob
import html
import os
import re
import shutil
import subprocess
import sys
import tempfile
import urllib.request

# Pass a model alias to `claude --model` (e.g. "haiku" / "sonnet") to force one;
# empty = the subscription default. Haiku is fastest/cheapest if your plan allows it.
CLAUDE_MODEL = ""
UA = "Mozilla/5.0 (Macintosh) dbms-digest-summarizer/1.0"
MAX_CHARS = 12000


def find_claude() -> str | None:
    """Locate the Claude Code CLI — bundled in the editor extension, or on PATH."""
    patterns = [
        "~/.cursor/extensions/anthropic.claude-code-*/resources/native-binary/claude",
        "~/.vscode/extensions/anthropic.claude-code-*/resources/native-binary/claude",
        "~/.vscode-server/extensions/anthropic.claude-code-*/resources/native-binary/claude",
    ]
    cands: list[str] = []
    for p in patterns:
        cands += glob.glob(os.path.expanduser(p))
    cands.sort(reverse=True)              # newest version string first
    onpath = shutil.which("claude")
    if onpath:
        cands.append(onpath)
    return cands[0] if cands else None


def fetch_text(url: str) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    raw = urllib.request.urlopen(req, timeout=15).read().decode("utf-8", "replace")
    raw = re.sub(r"(?is)<(script|style|noscript|head).*?</\1>", " ", raw)
    text = re.sub(r"(?s)<[^>]+>", " ", raw)
    return html.unescape(re.sub(r"\s+", " ", text)).strip()[:MAX_CHARS]


def summarize(claude: str, url: str, title: str, article: str) -> str:
    prompt = (
        "Ты делаешь сжатую выжимку технической статьи для опытного инженера по СУБД/PostgreSQL, "
        "которого раздражает маркетинговая вода. Выведи ТОЛЬКО саму выжимку — без вступлений, "
        "заголовков, markdown и фраз вроде «Вот». Напиши 3–5 простых предложений ПО-РУССКИ: "
        "(1) что это, (2) конкретная техническая суть, (3) почему это важно для DBA / хакера баз "
        "данных. Если на странице мало текста, пейволл или не по теме — скажи это одним "
        "предложением, не выдумывай.\n\n"
        f"Title: {title}\nURL: {url}\n\nСтатья:\n{article}"
    )
    cmd = [claude, "-p"]
    if CLAUDE_MODEL:
        cmd += ["--model", CLAUDE_MODEL]
    # Run in a neutral cwd so it doesn't load a project's CLAUDE.md / MCP config.
    proc = subprocess.run(cmd, input=prompt, text=True, capture_output=True,
                          cwd=tempfile.gettempdir(), timeout=180)
    out = (proc.stdout or "").strip()
    if proc.returncode != 0 or not out:
        raise RuntimeError((proc.stderr or "").strip() or "claude returned no output")
    return out


def card_html(title: str, url: str, body: str, *, ok: bool = True) -> str:
    esc = html.escape
    accent = "#9ec5ff" if ok else "#ffb27f"
    label = "Claude Code · subscription" + (f" · {CLAUDE_MODEL}" if CLAUDE_MODEL else "")
    return f"""<!DOCTYPE html><html><head><meta charset="utf-8">
<title>{esc(title)} — DBMS Digest summary</title>
<style>
  body {{ margin:0; background:#0d1b2e; color:#e8eef7;
         font:15px/1.55 -apple-system,BlinkMacSystemFont,system-ui,sans-serif; }}
  .wrap {{ max-width:680px; margin:6vh auto; padding:26px 30px;
           background:rgba(255,255,255,.03); border:1px solid rgba(158,197,255,.18);
           border-radius:16px; }}
  .tag {{ font-size:11px; letter-spacing:1px; text-transform:uppercase; color:{accent}; }}
  h1 {{ font-size:20px; margin:6px 0 14px; }}
  h1 a {{ color:#fff; text-decoration:none; }} h1 a:hover {{ color:{accent}; }}
  p.body {{ font-size:15.5px; color:#d6e2f2; white-space:pre-wrap; }}
  .foot {{ margin-top:18px; font-size:13px; }}
  .foot a {{ color:{accent}; text-decoration:none; }}
  .muted {{ color:#7f93ad; font-size:12px; margin-top:18px; }}
</style></head><body><div class="wrap">
  <div class="tag">✨ {esc(label)}</div>
  <h1><a href="{esc(url)}">{esc(title)}</a></h1>
  <p class="body">{esc(body)}</p>
  <div class="foot">→ <a href="{esc(url)}">Open the original article</a></div>
  <div class="muted">Generated by DBMS Digest widget via the Claude Code CLI.</div>
</div></body></html>"""


def open_card(html_text: str) -> None:
    fd, path = tempfile.mkstemp(prefix="dbms-summary-", suffix=".html")
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        f.write(html_text)
    if not os.environ.get("DBMS_SUMMARY_NO_OPEN"):
        subprocess.run(["open", path], check=False)
    print(path)


def compute(url: str, title: str) -> tuple[str, bool]:
    """Return (summary_or_error_text, ok)."""
    claude = find_claude()
    if not claude:
        return ("Не найден CLI Claude Code (расширение Cursor/VS Code, "
                "~/.cursor/extensions/anthropic.claude-code-*/…/claude). "
                "Проверь, что расширение установлено и ты залогинена.", False)
    try:
        article, note = fetch_text(url), ""
    except Exception as e:
        article, note = "", f"(не удалось загрузить страницу: {e})"
    try:
        summary = summarize(claude, url, title, article or note or "(нет текста)")
    except Exception as e:
        return (f"Claude не ответил: {e}", False)
    return (summary + (f"\n\n{note}" if note else ""), True)


def main() -> None:
    inline = bool(os.environ.get("DBMS_SUMMARY_INLINE")) or "--inline" in sys.argv
    args = [a for a in sys.argv[1:] if a != "--inline"]
    if not args:
        print("usage: summarize.py <url> [title]", file=sys.stderr)
        sys.exit(2)
    url = args[0]
    title = args[1] if len(args) > 1 else url

    text, ok = compute(url, title)
    if inline:
        print(text)                       # widget reads stdout and shows it inline
    else:
        open_card(card_html(title, url, text, ok=ok))


if __name__ == "__main__":
    main()
